---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      addresses:
      - 192.168.1.2/25
      routes:
        - to: default
          via: 192.168.1.1
    eth2:
      addresses:
      - 192.168.56.42/24
