---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      addresses:
      - 192.168.2.130/26
      routes:
        - to: default
          via: 192.168.2.129
    eth2:
      addresses:
      - 192.168.56.32/24
